language: ruby
rvm:
  - 2.4.0

install: ./script/bootstrap
script: bundle exec rake test:core rubocop build

matrix:
  include:
    - language: go
      go: 1.7.x
      before_script: ./script/setup/go
      script: bundle exec rake test:go
