#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

bundle install --path vendor/gems

# cd test/fixtures
#
# if [ -n "$(which bundle)" ]; then
#   pushd bundler
#   bundle install --path vendor/gems
#   popd
# fi
#
# # Install bower fixtures
# if [ -n "$(which bower)" ]; then
#   pushd bower
#   bower install
#   popd
# fi
